variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  
trigger:
- master

stages: 
  - stage: Build

    pool: NHSX

    variables:
      buildConfiguration: 'Release'

    jobs:
    - job: Build
      steps:
      - task: DotNetCoreCLI@2
        displayName: Restore
        inputs:
          command: restore
          projects: '**/*.csproj'
          noCache: true
          
      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          command: build
          projects: '**/*.csproj'
          arguments: '--configuration $(buildConfiguration)'
          
      - task: CopyFiles@2
        displayName: 'Copy files to directory'
        condition: always()
        inputs:
          SourceFolder: $(Build.SourcesDirectory)
          Contents: |
            **/*
            !.git/**/*
          TargetFolder: $(Build.ArtifactStagingDirectory)
                

  - stage: Release
    pool: NHSX
      
    variables:
      buildConfiguration: Release

    jobs:
    - deployment: Release
      environment: Release
      strategy:
        runOnce:
          deploy:
            steps:
              - task: VSTest@2
                displayName: 'Execute Tests'
                inputs:
                  testFiltercriteria: 'Category=QuickTest'
                  testSelector: testAssemblies
                  testAssemblyVer2: |
                    $(Agent.BuildDirectory)/**/*NexTest.DotNetCore.Framework.dll
                    !$(Agent.BuildDirectory)/**/obj/**

